version: '3.8'


networks:
  casino-net:
    driver: bridge


volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:

services:

  # 1. MySQL Database
  mysql_db:
    image: mysql:8.0
    container_name: mysql_casino_db
    restart: always
    environment:
      # Credenciales de acceso
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casino_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      # Puerto para conexión
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
     
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - casino-net

  # 2. Redis 
  redis_cache:
    image: redis:6.2-alpine
    container_name: redis_casino_cache
    restart: always
    command: redis-server --appendonly yes
    ports:
      # Puerto para conexión 
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - casino-net

  # 3. RabbitMQ
  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_casino_broker
    restart: always
    ports:
      # Puerto de mensajería
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - casino-net
